apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dvid5jw9t-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/dvid5jw9t-java-quarkus-gitops